name: Java CI

on:
  push:
    branches: [ "main", "Java"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'  # Or 'zulu', 'adopt', etc.

    - name: Build and run Java code
      run: |
        javac BasicJava.java
        java BasicJava
